modLoader = "javafml"
loaderVersion = "[38,)"
license = "${license_name}"
issueTrackerURL = "${github_url}/issues"
showAsResourcePack = false

[[mods]]
modId = "fireplacelib"
version = "${version}"
displayName = "${readable_name}"
updateJSONURL = "${forge_update_json_url}"
displayURL = "${forge_curseforge_url}"
logoFile = "${logo_filename}"
credits = ""
authors = "The_Fireplace"
description = "${mod_description}"

[[dependencies.fireplacelib]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fireplacelib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fireplacelib]]
modId = "annotateddi"
mandatory = true
versionRange = "[4,5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fireplacelib]]
modId = "cloth_config"
mandatory = false
versionRange = "[6,7)"
ordering = "NONE"
side = "CLIENT"