modLoader = "javafml"
loaderVersion = "[48,)"
license = "${license_name}"
issueTrackerURL = "${github_url}/issues"
showAsResourcePack = false

[[mods]]
modId = "fireplacelib"
version = "${version}"
displayName = "${readable_name}"
updateJSONURL = "${forge_update_json_url}"
displayURL = "${modrinth_url}"
logoFile = "${logo_filename}"
credits = ""
authors = "The_Fireplace"
description = "${mod_description}"

[[dependencies.fireplacelib]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fireplacelib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fireplacelib]]
modId = "annotateddi"
mandatory = true
versionRange = "[4,5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fireplacelib]]
modId = "cloth_config"
mandatory = false
versionRange = "[12,)"
ordering = "NONE"
side = "CLIENT"